"""Alteração atributos Place

Revision ID: 11916f191efb
Revises: c8f802e62ce7
Create Date: 2025-06-23 23:44:47.582632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11916f191efb'
down_revision: Union[str, None] = 'c8f802e62ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('description', sa.String(), nullable=True))
    op.add_column('places', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'image_url')
    op.drop_column('places', 'description')
    # ### end Alembic commands ###
