"""Cia tabela Preference

Revision ID: 2696478c446c
Revises: 7d231df2e55d
Create Date: 2025-06-03 18:37:50.896955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2696478c446c'
down_revision: Union[str, None] = '7d231df2e55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_preferences_id', table_name='preferences')
    #op.drop_table("preferences", cascade=True)
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['preferences.id'], name='user_preferences_preference_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'preference_id', name='user_preferences_pkey')
    )
    op.create_table('preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='preferences_pkey'),
    sa.UniqueConstraint('name', name='preferences_name_key')
    )
    op.create_index('ix_preferences_id', 'preferences', ['id'], unique=False)
    # ### end Alembic commands ###
