"""Remoção dos Enums

Revision ID: 7d231df2e55d
Revises: 9a85aec75f40
Create Date: 2025-05-27 19:10:49.054851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d231df2e55d'
down_revision: Union[str, None] = '9a85aec75f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    op.create_table('place_type',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'type_id')
    )
    op.drop_column('places', 'type')
    op.drop_column('users', 'current_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('places', sa.Column('type', postgresql.ENUM('RESTAURANTE', 'PONTO_TURISTICO', 'BAR', 'FESTA', 'SHOW', 'MUSEUM', 'PARK', name='placetypeenum'), autoincrement=False, nullable=False))
    op.drop_table('place_type')
    op.drop_index(op.f('ix_type_id'), table_name='type')
    op.drop_table('type')
    # ### end Alembic commands ###
