"""Adiciona atributo date

Revision ID: 7f318aaa7ec5
Revises: 1eeb1c329375
Create Date: 2025-09-15 20:17:49.868325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f318aaa7ec5'
down_revision: Union[str, None] = '1eeb1c329375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'date')
    # ### end Alembic commands ###
