"""Alteracoes ScheduleItem

Revision ID: 8864166c1721
Revises: 7f318aaa7ec5
Create Date: 2025-09-29 20:44:50.195597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8864166c1721'
down_revision: Union[str, None] = '7f318aaa7ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_items', 'description')
    # ### end Alembic commands ###
